digital_abc_quiz:
    resource: "@DigitalABCQuizBundle/Resources/config/routing.yml"
    prefix:   /quiz/

digital_abc_main:
    resource: "@DigitalABCMainBundle/Resources/config/routing.yml"
    prefix:   /

