parameters:
#    digital_abc_main.example.class: DigitalABC\MainBundle\Example

services:
#    digital_abc_main.example:
#        class: %digital_abc_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
