digital_abc_quiz_homepage:
    pattern:  /
    defaults: { _controller: DigitalABCQuizBundle:Default:index }

digital_abc_quiz_challenge:
    pattern:  /challenge/{id}
    defaults: { _controller: DigitalABCQuizBundle:Default:challenge }

digital_abc_quiz_api_save_result:
    pattern:  /api/result/save
    defaults: { _controller: DigitalABCQuizBundle:Api:saveResult }
