parameters:
#    digital_abc_quiz.example.class: DigitalABC\QuizBundle\Example

services:
#    digital_abc_quiz.example:
#        class: %digital_abc_quiz.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
